/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

//import consultas.VarCon;
import Variables.Var;
import java.sql.Date;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author migue
 */
public class ImportarHistoria extends javax.swing.JInternalFrame {

    Var san;

    /**
     * Creates new form ImportarHistoria
     *
     * @param wv
     */
    public ImportarHistoria(Var wv) {
        initComponents();
        san = wv;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historia = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        inp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tot = new javax.swing.JTextField();
        por = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setTitle("Ingreso de datos....");

        historia.setColumns(20);
        historia.setRows(5);
        jScrollPane1.setViewportView(historia);

        jButton1.setText("importar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Importando :");

        jLabel2.setText(" de");

        tot.setText("jTextField2");

        por.setText("jTextField3");

        jLabel3.setText("%");

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(412, 412, 412)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inp, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tot, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(por, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(70, 70, 70)
                .addComponent(jButton2)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(por, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO historia_t VALUES "
                + "(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"
                + "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        String[] lineas = historia.getText().split("\n");
        long numcam = lineas.length;
//        String nums=);
        tot.setText(String.valueOf(numcam));
        try {
            PreparedStatement borra = san.getCon().prepareStatement("DELETE FROM historia_t");
            borra.execute();
            PreparedStatement ps = san.getCon().prepareStatement(sql);
            int fini = lineas.length - 1;
            for (int a = 1; a < lineas.length - 1; a++) {
                String[] campos = lineas[a].split("\\t"); 
//                String[] campos = lineas[a].split(",");
                ps.setString(1, campos[0]);
                ps.setDate(2, Date.valueOf(campos[1]));
                ps.setDate(3, Date.valueOf(campos[1]));
                System.out.println("actualizando : " + a + " de " + fini + "   " + (a / fini) + "%");
                ps.setString(4, campos[3]);
                ps.setString(5, ajusta(campos[4], 8).trim());
                ps.setString(6, campos[5]);
                ps.setDate(7, Date.valueOf(campos[7]));
                ps.setDate(8, Date.valueOf(campos[7]));
                ps.setDouble(9, Double.valueOf(campos[8]));
                ps.setDouble(10, Double.valueOf(campos[9]));
                ps.setDouble(11, Double.valueOf(campos[10]));
                ps.setDouble(12, Double.valueOf(campos[11]));
                ps.setDouble(13, Double.valueOf(campos[12]));
                ps.setDouble(14, Double.valueOf(campos[13]));
                ps.setDouble(15, Double.valueOf(campos[14]));
                ps.setString(16, campos[15]);
                ps.setString(17, campos[16]);
                ps.setDouble(18, Double.valueOf(campos[17]));
                ps.setDouble(19, Double.valueOf(campos[18]));
                ps.setDouble(20, 0.00);
                ps.setString(21, campos[20]);
                ps.setString(22, campos[21]);
                ps.setString(23, campos[22]);
                int largo = campos[23].length();
                if (largo > 99) {
                    largo = 98;
                }
                ps.setString(24, campos[23].substring(largo));
                ps.setString(25, campos[24]);
                ps.setString(26, campos[25]);
                ps.setString(27, campos[26]);
                ps.setString(28, campos[27]);
                ps.setString(29, campos[28].trim());
                largo = campos[29].length();
                if (largo > 30) {
                    largo = 30;
                }
                ps.setString(30, campos[29].substring(largo));
                largo = campos[30].length();
                if (largo > 10) {
                    largo = 10;
                }
                ps.setString(31, campos[30].substring(largo));
                ps.setString(32, campos[31]);
                ps.setString(33, campos[32]);
                ps.setString(34, campos[33]);
                ps.setString(35, campos[34]);
                ps.setString(36, campos[35]);
                ps.setString(37, campos[36]);
                ps.setString(38, campos[37]);
                ps.setString(39, campos[38]);
                ps.setString(40, campos[39]);
                ps.setString(41, campos[40]);
                ps.setString(42, campos[41]);
                ps.setString(43, campos[42].trim());
                ps.setString(44, campos[43]);
                ps.setString(45, campos[44]);
                ps.setString(46, campos[45]);
                ps.setString(47, campos[46]);
                ps.setString(48, campos[47]);
                ps.setString(49, campos[48]);
                ps.setString(50, campos[49]);
                ps.setString(51, campos[50]);
                ps.setString(52, campos[51]);
                ps.setString(53, campos[52]);
                ps.setString(54, campos[53]);
                ps.setString(55, campos[54]);
                ps.setString(56, campos[55]);
                ps.setString(57, campos[56]);
                ps.setString(58, campos[57]);
                ps.setString(59, campos[58]);
                ps.setString(60, campos[59]);
                ps.setString(61, campos[60]);
                ps.setDouble(62, Double.valueOf(campos[61]));
                ps.setDouble(63, Double.valueOf(campos[62]));
                ps.setDouble(64, Double.valueOf(campos[63]));
                ps.setDouble(65, Double.valueOf(campos[64]));
                ps.setDouble(66, Double.valueOf(campos[65]));
                ps.setDouble(67, Double.valueOf(campos[66]));
                ps.setDouble(68, Double.valueOf(campos[67]));
                ps.setDouble(69, Double.valueOf(campos[68]));
                ps.setString(70, campos[69]);
                ps.setString(71, campos[70]);
                ps.setString(72, campos[71]);
                ps.setString(73, campos[72]);
                ps.setString(74, "");
                int lago=campos[26].indexOf("-");
                ps.setString(75,campos[26].substring(0, lago));
                System.out.println(campos[26].substring(0, lago));
                inp.setText(String.valueOf(a));
                double po = a / numcam;
                ps.executeUpdate();
                por.setText(String.valueOf(po));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ImportarHistoria.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        historia.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea historia;
    private javax.swing.JTextField inp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField por;
    private javax.swing.JTextField tot;
    // End of variables declaration//GEN-END:variables

    private static java.sql.Date convert(java.util.Date uDate) {
//Date sDate = null;
        try {
            java.sql.Date sDate = new java.sql.Date(uDate.getTime());
            return sDate;
        } catch (Exception err) {
            java.sql.Date sDate = new java.sql.Date(0);
            return sDate;
        }

    }

    private java.util.Date ParseFecha(String fecha) {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        java.util.Date fechaDate = null;
        try {
            fechaDate = formato.parse(fecha);
        } catch (ParseException ex) {
            System.out.println(ex);
        }
        return fechaDate;
    }

    private String ajusta(String campo, int i) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        String sale = "";
        String espacio = " ";
//        int largo = campo.trim().length();
//        if (largo < i) {
        for (int a = 0; a <= i; a++) {
            espacio = espacio + " ";
        }
        sale = campo.trim().concat(espacio);
//        }

        return sale.substring(0, i);
    }

}
